name: Deploy to AlwaysData

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements file

    #- name: Run tests
    #  run: |
    #    python -m unittest discover tests  # Adjust this to your test command

    - name: Deploy to AlwaysData
      env:
        PRIVATE_KEY: ${{ secrets.ALWAYSDATA_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.ALWAYSDATA_HOST }}
        USER: ${{ secrets.ALWAYSDATA_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" --exclude '.git*' --exclude 'tests' --delete ./ ${USER}@${HOST}:~/david-lloyd/
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} 'cd ~/david-lloyd && pip install -r requirements.txt'
        rm -f private_key